kramdown:
  input: GFM
  hard_wrap: false
encoding: utf-8
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - '*.sublime-*'
  - browserslist
  - CNAME
  - Gemfile*
  - node_modules
  - package.json
  - sftp_batchfile*
  - webpack.config.js
  - TODO.md
  - yarn.lock
  - npm-debug.log
sass:
  style: compressed
  sass_dir: _sass
permalink: /:categories/:year/:month/:slug/
timezone: Europe/Paris
collections:
  concerts:
    output: true
  profs:
    output: true
    permalink: /les-profs/:name/
  activites:
    output: true
    permalink: /activites/:name/
  nouvelles:
    output: false
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "ressources"
    values:
      robots: noindex, nofollow
  - scope:
      path: "chanter"
    values:
      layout: chanter
  - scope:
      path: "progresser"
    values:
      layout: chanter
  - scope:
      path: _concerts
    values:
      layout: concert
  - scope:
      path: _profs
    values:
      layout: prof
  - scope:
      path: _activites
    values:
      layout: chanter
prose:
  rooturl: ''
  metadata:
    "":
      - name: "published"
        field:
          label: "Publié"
          element: "checkbox"
          value: "true"
      - name: "description"
        field:
          label: "Description"
          element: text
          help: "Description pour Google"
          value: ""
    
    chanter/_posts:
      - name: "subtitle"
        field:
          label: "Sous-titre"
          help: "Sous-titre affiché en vert"
          element: text
          value: ""
      - name: "flash"
        field:
          label: "Sous-titre"
          help: "Gros text affiché en jaune avec des notes musicales autour"
          element: text
          value: ""
      
      - name: "image"
        field:
          label: "Lien de l'image qui sera affichée en tête des infos pratiques (facultatif)"
          help: "Par exemple, le logo de Céladon"
          element: text
          value: ""
      - name: "image_lien"
        field:
          label: "Lien utilisé si on clique sur l'image (facultatif)"
          help: "Par exemple, le site de Céladon"
          element: text
          value: ""
      
      - name: "profs"
        field:
          label: "Profs"
          element: multiselect
          options: "https://amusaly.github.io/profs.jsonp"
    
    _concerts:
      - name: "affiche"
        field:
          element: "text"
          help: "Chemin de l'affiche"
          value: ""
      - name: "concert_1_date"
        field:
          element: "text"
          help: "Date du 1er concert"
          value: ""
      - name: "concert_1_lieu"
        field:
          element: "text"
          help: "Lieu du 1er concert"
          value: ""
      - name: "concert_1_adresse"
        field:
          element: "text"
          help: "Adresse du lieu du 1er concert"
          value: ""
          
      - name: "concert_2_date"
        field:
          element: "text"
          help: "Date du 1er concert"
          value: ""
      - name: "concert_2_lieu"
        field:
          element: "text"
          help: "Lieu du 1er concert"
          value: ""
      - name: "concert_2_adresse"
        field:
          element: "text"
          help: "Adresse du lieu du 1er concert"
          value: ""

  ignore:
    - /_css
    - /_includes
    - /_jsx
    - /_layouts
    - /_site
    - /_stats
    - /compiled_assets
    - /images
    - /node_modules
    - .gitignore
    - .stylelintrc
    - .uploaded.sha1
    - Gemfile
    - Gemfile.lock
    - Omnia*
    - TODO.md
    - amusaly.sublime-project
    - browerslist
    - midi.html
    - "*.js"
    - CNAME
    - "*.pdf"
    - browserslist
    - favicon.ico
    - package.json
    - _config.yml
    - "*.html"
    - "*.ignore"
    - /ressources
  siteurl: "https://amusaly.fr/"
  media: images