kramdown:
  input: GFM
  hard_wrap: false
encoding: utf-8
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - '*.sublime-*'
  - browserslist
  - CNAME
  - Gemfile*
  - node_modules
  - package.json
  - sftp_batchfile*
  - webpack.config.js
  - TODO.md
  - yarn.lock
  - npm-debug.log
sass:
  style: compressed
  sass_dir: _sass
permalink: /:categories/:year/:month/:slug/
timezone: Europe/Paris
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "ressources"
    values:
      robots: noindex, nofollow
  -
    scope:
      path: "chanter"
    values:
      layout: chanter
  -
    scope:
      path: "progresser"
    values:
      layout: chanter
  -
    scope:
      path: "concerts"
      type: "posts"
    values:
      layout: concert
prose:
  rooturl: ''
  ignore:
    - /_css
    - /_includes
    - /_jsx
    - /_layouts
    - /_site
    - /_stats
    - /compiled_assets
    - /images
    - /node_modules
    - .gitignore
    - .stylelintrc
    - .uploaded.sha1
    - Gemfile
    - Gemfile.lock
    - Omnia*
    - TODO.md
    - amusaly.sublime-project
    - browerslist
    - midi.html
    - "*.js"
    - CNAME
    - "*.pdf"
    - browserslist
    - favicon.ico
    - package.json
    - _config.yml
  siteurl: 'https://amusaly.github.io/'
  relativeLinks: 'https://amusaly.github.io/links.jsonp'
  media: 'images'
  metadata:
    concerts/_posts:
      - name: "title"
        field:
          - element: "text"
          - value: ""
          - placeholder: "Titre affiché par le navigateur"
          - value: ""
      - name: "description"
        field:
          - element: "text"
          - placeholder: "Description pour Google"
          - value: ""
      - name: "affiche"
        field:
          - element: "text"
          - placeholder: "Chemin de l'affiche"
          - value: ""
      - name: "concert_1_date"
        field:
          - element: "text"
          - placeholder: "Date du 1er concert"
          - value: ""
      - name: "concert_1_lieu"
        field:
          - element: "text"
          - placeholder: "Lieu du 1er concert"
          - value: ""
      - name: "concert_1_adresse"
        field:
          - element: "text"
          - placeholder: "Adresse du lieu du 1er concert"
          - value: ""
